### PR TITLE
Catch two divisions by zero

### PR DESCRIPTION
**Pull request by brenreid**
Hi Tom,

When looking at some PWC igcs i found a couple of division by zero call back errors.
The quick hacks below seem to sort them out?

Bren

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks @brenreid for the patch. If `dt` is zero it means that two consecutive records in the IGC file have the same timestamp. A better solution would be to remove records with duplicate timestamps. Could you attach the IGC files that trigger the problem here so I can reproduce it?

**Comment by brenreid** [comment]
I agree there must be duplicate B-records. Possibly a flaky instrument or
instrument firmware?
I think I found the errors while looking at PWC Brazil 2016 first task.

http://pwca.org/results/results/t_1_1.zip

**Comment by brenreid** [comment]
0619.igc from that zip file shows the behaviour
Compass flight instrument

**Comment by brenreid** [comment]
Also 

0050.igc 
0231.igc
0217.igc

all Compass

**Comment by twpayne** [comment]
Thanks @brenreid, this should now be fixed.

**Pull request closed without merging**
